spring.application.name=userproject
# URL de conexión H2 (en memoria, para desarrollo)
spring.datasource.url=jdbc:h2:mem:userdb
spring.datasource.driverClassName=org.h2.Driver
# Nombre de usuario y contraseña (pueden ser genéricos)
spring.datasource.username=usuario
spring.datasource.password=
# Habilitar la consola web de H2 (opcional)


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql= true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# Puerto de la consola (opcional, por defecto 8080/h2-console)
# Inicializar el esquema y datos (opcional, para scripts .sql)
# spring.sql.init.mode=always
# spring.sql.init.schema-locations=classpath:schema.sql,classpath:data.sql
